#!/usr/bin/env python

"""
CLI interface to the RED utility
"""

__version__ = "1"
__author__ = "Jerome Renard <jerome.renard@gmail.com>"
__copyright__ = """\
Copyright (c) 2008-2010 Mark Nottingham

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

import sys
assert sys.version_info[0] == 2 and sys.version_info[1] >= 5, "Please use Python 2.5 or greater"

from optparse import OptionParser
import red
import red_speak as rs
import red_header
import string

nl = "\n"

class OutputFormatter(object):

    msg_categories = [
        rs.c.GENERAL, rs.c.CONNECTION, rs.c.CONNEG, rs.c.CACHING, rs.c.VALIDATION, rs.c.RANGE
    ]

    def __init__(self, droid):
        self.droid = droid

    def print_headers(self):
        return

    def print_recommendations(self):
        print ""
        nl.join([str(self.print_recommendation(str(category))) for category in self.msg_categories])

    def print_recommendation(self):
        return

class TxtOutputFormatter(OutputFormatter):
    def print_headers(self):
        print "Response Headers:"
        print nl.join(["%s:%s" % header for header in self.droid.res_hdrs])

    def print_recommendation(self, category):
        messages = [msg for msg in self.droid.messages if msg.category == category]
        if not messages:
            return nl
        out = []
        if [msg for msg in messages]:
            out.append(u"%s:" % category)
        for m in messages:
            out.append(
                "%s" % (self.colorize(m.level, m.summary["en"] % m.vars))
            )
            smsgs = [msg for msg in getattr(m.subrequest, "messages", []) if msg.level in [rs.l.BAD]]
            if smsgs:
                out.append("")
                for sm in smsgs:
                    out.append(
                        "%s" %
                        (self.colorize(sm.level, sm.summary["en"] % sm.vars))
                    )
                out.append("")
        out.append("")
        print nl.join(out)

    def colorize(self, level, string):
        # info
        color_start = "\033[0;32m"
        color_end   = "\033[0;39m"

        if level == "good":
            color_start = "\033[1;32m"
            color_end   = "\033[0;39m"

        if level == "bad":
            color_start = "\033[1;31m"
            color_end   = "\033[0;39m"

        if level == "warning":
            color_start = "\033[1;33m"
            color_end   = "\033[0;39m"

        return color_start + string + color_end


class RstOutputFormatter(OutputFormatter):
    def print_headers(self):
        print "Response headers"
        print "----------------"
        print ""
        print "::"
        print ""
        print nl.join([ "\t%s:%s" % header for header in self.droid.res_hdrs])
        #declaring flag definitions
        print RstOutputFormatter.flag_definition()

    def print_recommendation(self, category):
        messages = [msg for msg in self.droid.messages if msg.category == category]
        if not messages:
            return nl
        out = []
        if [msg for msg in messages]:
            out.append("%s:\n" % category)
        for m in messages:
            out.append(
                "- %s" %
                (self.flagize(m.level, m.summary["en"] % m.vars))
            )
            smsgs = [msg for msg in getattr(m.subrequest, "messages", []) if msg.level in [rs.l.BAD]]
            if smsgs:
                out.append("")
                for sm in smsgs:
                    out.append(
                        "%s" %
                        (self.flagize(sm.level, sm.summary["en"] % sm.vars))
                    )
                out.append("")
        out.append("")
        print nl.join(out)

    def flagize(self, level, string):
        # info
        flag = "|flag-info|"

        if level == "good":
            flag = "|flag-good|"

        if level == "bad":
            flag = "|flag-bad|"

        if level == "warning":
            flag = "|flag-warning|"

        return flag + " " + string

    @staticmethod
    def flag_definition():
        flag_dir = "web/icon/"
        flag_definition_list = {
            "good":"accept1.png", "bad":"remove-16.png", "warning":"yellowflag1.png", "info":"infomation-16.png"
        }

        out = []
        out.append("")
       
        for flag, icon in flag_definition_list.items():
            out.append(".. |flag-" + flag + "| image:: " + flag_dir + icon + nl + "             :width: 16px")

        return nl.join(out)

class OutputFormatterFactory(object):
    @staticmethod
    def create(output_format, red):
        if output_format == "txt":
           return TxtOutputFormatter(red)
        elif output_format == "rst":
            return RstOutputFormatter(red)

def dump(obj):
  for attr in dir(obj):
    print "obj.%s = %s" % (attr, getattr(obj, attr))

def main():
    usage   = """Usage: %prog [options] <url>"""
    version = """Redbot: The Resource Expert Droid, version %s, http://redbot.org/ """ % red.__version__

    available_output_formats = ["txt", "rst"]

    option_parser = OptionParser(usage=usage, version=version)
    option_parser.set_defaults(version=False,output_format="txt", show_recommendations=False)

    option_parser.add_option("-o", "--output-format",
                             action="store", dest="output_format",
                             help="output format, either txt, rst, default : txt")

    option_parser.add_option("-r", "--show-recommendations",
                             action="store_true", dest="show_recommendations",
                             help="wether or not to show recommendations")

    (options, args) = option_parser.parse_args()
    
    if len(args) != 1:
        option_parser.error("Please specify a URL")

    if options.output_format not in available_output_formats:
        option_parser.error("Please provide a correct output format")

    url = args[0]
    droid = red.ResourceExpertDroid(url)

    OutputFormatter = OutputFormatterFactory.create(options.output_format, droid)
    OutputFormatter.print_headers()

    if options.show_recommendations == True:
        OutputFormatter.print_recommendations()

if __name__ == "__main__":
    main()