

JSFILES = jquery.js jquery.hoverIntent.js prettify.js
CSSFILES = red_style.css prettify.css


all: script.js style.css

clean:
	rm script.js style.css

script.js:
	cat $(JSFILES) > script.js
	
style.css:
	cat $(CSSFILES) > style.css